'use client';
import {useMemo,useState} from 'react';
const nav=[['⌂','Inici'],['◫','Preinscripcions'],['▣','Matrícules'],['◷','Reserves'],['◎','Places i vacants'],['◌','Llistes d’espera'],['♙','Famílies'],['□','Documents'],['↗','Comunicacions']];
const initials=(s:string='')=>s.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
const money=(n:any)=>`${Number(n||0).toFixed(2).replace('.',',')} €`;
export default function Gestio(){
 const [secret,setSecret]=useState('');const [data,setData]=useState<any>(null);const [err,setErr]=useState('');const [q,setQ]=useState('');const [status,setStatus]=useState('Tots');const [selected,setSelected]=useState<any>(null);const [saving,setSaving]=useState(false);
 async function load(){setErr('');const r=await fetch('/api/admin/dashboard',{headers:{'x-activat-admin-secret':secret}});const j=await r.json();if(!r.ok){setErr(j.error||'No autoritzat');return}setData(j)}
 async function saveSelected(){if(!selected)return;setSaving(true);const r=await fetch(`/api/admin/registrations/${selected.id}`,{method:'PATCH',headers:{'content-type':'application/json','x-activat-admin-secret':secret},body:JSON.stringify({is_member:selected.is_member,registered_children_count:selected.registered_children_count,child_order:selected.child_order,discount_amount:selected.discount_amount,discount_label:selected.discount_label,status:selected.status})});const j=await r.json();setSaving(false);if(!r.ok){alert(j.error||'No s’ha pogut desar');return}setData((d:any)=>({...d,registrations:d.registrations.map((x:any)=>x.id===j.id?j:x)}));setSelected(j)}
 const rows=useMemo(()=>data?.registrations?.filter((r:any)=>{const text=`${r.code} ${r.student_name} ${r.activity_name} ${r.representative_name}`.toLowerCase();return text.includes(q.toLowerCase())&&(status==='Tots'||r.status===status)})||[],[data,q,status]);
 if(!data)return <main className="container"><div className="card loginCard"><div className="adminLock">⌁</div><span className="eyebrow">Àrea interna</span><h1 style={{fontSize:30,margin:'8px 0'}}>Secretaria ACTIVA’T</h1><p className="muted">Accés reservat a l’equip autoritzat de l’AFA Escola Sant Salvador.</p><div className="field" style={{marginTop:20}}><label>Clau interna</label><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Clau d’accés"/></div><button className="btn primary" style={{width:'100%',marginTop:12}} onClick={load}>Entrar a Secretaria →</button>{err&&<p className="pill bad" style={{marginTop:12}}>{err}</p>}<p className="help" style={{marginTop:15}}>La clau només s’utilitza per a aquesta sessió.</p></div></main>;
 return <main className="adminShell">
   <aside className="adminSide"><div className="adminBrand"><strong>ACTIVA’T</strong><span>Secretaria Virtual</span></div><div className="sideLabel">Gestió</div>{nav.map((n,i)=><a href="#" className={`sideLink ${i===1?'active':''}`} key={n[1]} onClick={e=>e.preventDefault()}><span className="sideDot">{n[0]}</span>{n[1]}{i===1&&<span style={{marginLeft:'auto'}} className="pill purple">{data.registrations.length}</span>}</a>)}<div className="sideLabel">Sistema</div><a href="#" className="sideLink" onClick={e=>e.preventDefault()}><span className="sideDot">⚙</span>Configuració</a><a href="/" className="sideLink"><span className="sideDot">↩</span>Tornar al web</a></aside>
   <section className="adminMain">
    <div className="adminTop"><div><span className="eyebrow">Panell de Secretaria</span><h1>Bon dia. Què gestionem avui?</h1><p>Controla preinscripcions, places, cobraments i incidències des d’un únic espai.</p></div><div className="adminActions"><button className="btn secondary" onClick={load}>↻ Actualitzar</button><button className="btn primary" onClick={()=>alert('Nou tràmit administratiu')}>＋ Nou tràmit</button></div></div>
    <div className="kpis"><div className="card kpi"><div className="kpiTop">Preinscripcions <span className="trend">actualitzat</span></div><strong>{data.kpis.Preinscripcions}</strong><span className="muted small">Expedients registrats</span></div><div className="card kpi"><div className="kpiTop">Actives</div><strong>{data.kpis.Actives}</strong><span className="muted small">En gestió</span></div><div className="card kpi"><div className="kpiTop">Places ocupades</div><strong>{data.kpis['Places ocupades']}</strong><span className="muted small">Matrícules confirmades</span></div><div className="card kpi"><div className="kpiTop">Pendent de cobrament</div><strong>{data.kpis.Pendent}</strong><span className="muted small">Imports pendents</span></div></div>
    <div className="adminGrid">
      <section className="card"><div className="panelTitle"><div><h2>Preinscripcions</h2><span className="muted small">Obre un expedient per revisar dades i corregir errors comunicats per la família.</span></div><span className="pill purple">{rows.length} visibles</span></div><div className="toolbar"><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cerca per codi, alumne, activitat o família…"/></div><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option>Tots</option>{Array.from(new Set(data.registrations.map((r:any)=>r.status))).map((s:any)=><option key={s}>{s}</option>)}</select></div><div className="tablewrap"><table className="table"><thead><tr><th>Expedient</th><th>Alumne/a</th><th>Activitat</th><th>Condició</th><th>Estat</th><th>Import</th><th></th></tr></thead><tbody>{rows.length?rows.map((r:any)=><tr key={r.id}><td><span className="code">{r.code}</span></td><td><div className="person"><span className="avatar">{initials(r.student_name)}</span><span><b>{r.student_name}</b><small className="muted" style={{display:'block'}}>{r.representative_name}</small></span></div></td><td>{r.activity_name}</td><td><span className="pill purple">{r.is_member?'Soci/a':'No soci/a'} · {Number(r.child_order)>=3?'3r+':`${r.child_order}r`}</span></td><td><span className={`pill ${r.status==='admesa'||r.status==='matriculada'?'ok':r.status==='eliminada'?'bad':'wait'}`}>{r.status}</span></td><td><b>{money(r.total_amount)}</b><small className="muted" style={{display:'block'}}>pagat {money(r.paid_amount)}</small></td><td><button className="btn secondary" onClick={()=>setSelected(r)}>Obrir</button></td></tr>):<tr><td colSpan={7}><div className="muted" style={{padding:25,textAlign:'center'}}>No hi ha expedients que coincideixin amb el filtre.</div></td></tr>}</tbody></table></div></section>
      <aside><section className="card"><div className="panelTitle"><h2>Accions ràpides</h2></div><div className="quickGrid"><button className="quick">＋ Nova preinscripció</button><button className="quick">▣ Places</button><button className="quick">€ Cobraments</button><button className="quick">□ Documents</button></div></section><section className="card" style={{marginTop:18}}><div className="panelTitle"><div><h2>Activitats</h2><span className="muted small">Ocupació actual</span></div></div><div className="miniList">{data.activities?.length?data.activities.map((a:any)=><div className="miniItem" key={a.id}><div><strong>{a.name}</strong><span style={{display:'block'}}>{a.capacity} places</span></div><span>{a.occupied||0}/{a.capacity}</span></div>):<div className="muted small">Les activitats configurades apareixeran aquí.</div>}</div></section><section className="card" style={{marginTop:18}}><span className="eyebrow">Regla de correcció</span><h3 style={{marginTop:7}}>La família s’ha equivocat?</h3><p className="muted small">Secretaria pot modificar la condició de soci/a, el nombre de fills/es registrats/des i l’ordre del fill/a sense haver de crear una nova preinscripció.</p></section></aside>
    </div>
   </section>
   {selected&&<div className="drawerOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="drawer"><div className="drawerHeader"><div><span className="eyebrow">Expedient {selected.code}</span><h2>{selected.student_name}</h2><p className="muted">{selected.activity_name} · {selected.representative_name}</p></div><button className="btn secondary" onClick={()=>setSelected(null)}>Tancar</button></div><hr className="divider"/><h3>Dades de la família</h3><div className="detailGrid"><div className="detailItem"><small>Soci/a</small><select className="select" value={selected.is_member?'si':'no'} onChange={e=>setSelected({...selected,is_member:e.target.value==='si'})}><option value="si">Soci/a</option><option value="no">No soci/a</option></select></div><div className="detailItem"><small>Fills/es registrats/des</small><input className="fieldInput" type="number" min="1" value={selected.registered_children_count||1} onChange={e=>setSelected({...selected,registered_children_count:Number(e.target.value)})}/></div><div className="detailItem"><small>Ordre del fill/a</small><select className="select" value={selected.child_order||1} onChange={e=>setSelected({...selected,child_order:Number(e.target.value)})}><option value={1}>1r fill/a</option><option value={2}>2n fill/a</option><option value={3}>3r o posterior</option></select></div><div className="detailItem"><small>Estat</small><select className="select" value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}><option>en revisió</option><option>admesa</option><option>matriculada</option><option>llista d’espera</option><option>eliminada</option></select></div></div><section className="discountBox" style={{marginTop:18}}><div className="row space"><div><span className="eyebrow">Descompte</span><h3 style={{marginTop:4}}>Correcció manual</h3></div><span className="pill purple">editable</span></div><div className="discountLine"><span>Descompte aplicat</span><input className="fieldInput" style={{width:100,textAlign:'right'}} type="number" step="0.01" min="0" value={selected.discount_amount||0} onChange={e=>setSelected({...selected,discount_amount:Number(e.target.value)})}/></div><div className="discountLine"><span>Motiu / etiqueta</span><input className="fieldInput" style={{width:230}} value={selected.discount_label||''} onChange={e=>setSelected({...selected,discount_label:e.target.value})}/></div><div className="totalLine row space"><span>Import final</span><span>{money(selected.total_amount)}</span></div></section><div className="notice" style={{marginTop:18}}>Aquesta correcció queda aplicada al mateix expedient. No cal demanar a la família que torni a fer la preinscripció.</div><div className="row" style={{marginTop:18}}><button className="btn primary" onClick={saveSelected} disabled={saving}>{saving?'Desant…':'Desar canvis'}</button><button className="btn secondary" onClick={()=>setSelected(null)}>Cancel·lar</button></div></aside></div>}
 </main>
}
