'use client';
import {useState} from 'react';

type Contact={name:string;phone:string;relation:string};
type Registration={code:string;status:string;activity:string;student:string;representative:string;birthDate:string;total:number;paid:number;emergencyContacts:Contact[];authorizedPeople:Contact[]};

export default function Consulta(){
 const [code,setCode]=useState('');const [surname,setSurname]=useState('');const [birthDate,setBirthDate]=useState('');const [registration,setRegistration]=useState<Registration>();const [matches,setMatches]=useState<Registration[]>([]);const [error,setError]=useState('');const [saved,setSaved]=useState('');const [loading,setLoading]=useState(false);
 async function identify(){setError('');setSaved('');setRegistration(undefined);setMatches([]);if(!code&&!surname){setError('Indica el número de preinscripció o el primer cognom.');return}if(!code&&!birthDate){setError('Per buscar per cognom cal indicar la data de naixement.');return}setLoading(true);const response=await fetch('/api/public/registrations/contacts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,surname,birthDate})});const json=await response.json();setLoading(false);if(!response.ok){setError(json.error||'No s’ha trobat la inscripció.');return}if(json.matches){setMatches(json.matches);return}setRegistration(json.registration)}
 function choose(item:Registration){setRegistration(item);setMatches([])}
 function setContact(type:'emergencyContacts'|'authorizedPeople',index:number,key:keyof Contact,value:string){setRegistration(current=>current?{...current,[type]:current[type].map((contact,i)=>i===index?{...contact,[key]:value}:contact)}:current)}
 function addContact(type:'emergencyContacts'|'authorizedPeople'){setRegistration(current=>current?{...current,[type]:[...current[type],{name:'',phone:'',relation:''}]}:current)}
 function removeContact(type:'emergencyContacts'|'authorizedPeople',index:number){setRegistration(current=>current?{...current,[type]:current[type].filter((_,i)=>i!==index)}:current)}
 async function saveContacts(){if(!registration)return;setLoading(true);setError('');const response=await fetch('/api/public/registrations/contacts',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({code:registration.code,surname,birthDate,emergencyContacts:registration.emergencyContacts,authorizedPeople:registration.authorizedPeople})});const json=await response.json();setLoading(false);if(!response.ok){setError(json.error||'No s’han pogut desar els contactes.');return}setRegistration(json.registration);setSaved('Contactes actualitzats correctament.')}
 function editor(title:string,type:'emergencyContacts'|'authorizedPeople',empty:string){const contacts=registration?.[type]||[];return <section className="contactEditor"><div className="row space"><div><h2>{title}</h2><p className="muted small">Afegeix cada persona en una fila. No cal escriure cap codi.</p></div><button className="btn secondary" onClick={()=>addContact(type)}>＋ Afegir persona</button></div>{contacts.map((contact,index)=><div className="contactRow" key={index}><div className="field"><label>Nom i cognoms</label><input value={contact.name} onChange={event=>setContact(type,index,'name',event.target.value)} placeholder="Nom de la persona"/></div><div className="field"><label>Telèfon</label><input type="tel" value={contact.phone} onChange={event=>setContact(type,index,'phone',event.target.value)} placeholder="600 000 000"/></div><div className="field"><label>Relació</label><input value={contact.relation} onChange={event=>setContact(type,index,'relation',event.target.value)} placeholder="Mare, pare, avi…"/></div><button className="iconButton" aria-label="Eliminar persona" title="Eliminar persona" onClick={()=>removeContact(type,index)}>×</button></div>)}{!contacts.length&&<div className="emptyContacts">{empty}</div>}</section>}
 return <main className="container"><section className="hero"><span className="eyebrow">Seguiment i actualització</span><h1>Consulta o actualitza una gestió</h1><p>Amb el número de preinscripció pots entrar directament. Si no el tens, utilitza el primer cognom i la data de naixement.</p></section><section className="card lookup"><div className="lookupGuide"><span className="lookupGuideIcon">⌕</span><div><b>Identifica la inscripció</b><small>El codi és suficient. La data només és necessària quan busques per cognom.</small></div></div><div className="lookupFormGrid"><div className="field"><label>Número de preinscripció</label><input value={code} onChange={event=>setCode(event.target.value.toUpperCase())} placeholder="AFA-26-ROB-001"/></div><div className="field"><label>Primer cognom de l’alumne/a</label><input value={surname} onChange={event=>setSurname(event.target.value)} placeholder="Martí"/></div><div className="field"><label>Data de naixement <span className="muted small">només si busques per cognom</span></label><input type="date" value={birthDate} onChange={event=>setBirthDate(event.target.value)}/></div></div><button className="btn primary" onClick={identify} disabled={loading}>{loading?'Comprovant…':'Identificar inscripció →'}</button>{error&&<p className="pill bad" style={{marginTop:14}}>{error}</p>}{saved&&<p className="pill ok" style={{marginTop:14}}>{saved}</p>}{matches.length>0&&<div className="matchList"><h3>Hem trobat més d’una coincidència</h3><p className="muted small">Selecciona l’alumne/a exacte abans de continuar.</p>{matches.map(item=><button className="matchItem" key={item.code} onClick={()=>choose(item)}><span><b>{item.student}</b><small>{item.activity} · {item.code}</small></span><span>Seleccionar →</span></button>)}</div>}{registration&&<div className="success registrationResult"><div className="row space"><div><span className="muted small">Inscripció seleccionada</span><div className="codeBox" style={{fontSize:18}}>{registration.code}</div></div><span className="pill wait">{registration.status}</span></div><div className="detailGrid" style={{marginTop:22}}><div className="detailItem"><small>Alumne/a</small><b>{registration.student}</b></div><div className="detailItem"><small>Activitat</small><b>{registration.activity}</b></div><div className="detailItem"><small>Representant</small><b>{registration.representative}</b></div></div>{editor('Persones autoritzades per recollir','authorizedPeople','Encara no hi ha persones autoritzades.')}{editor('Contactes d’emergència','emergencyContacts','Encara no hi ha contactes d’emergència.')}<button className="btn primary" onClick={saveContacts} disabled={loading}>{loading?'Desant…':'Desar contactes'}</button></div>}</section></main>}
