'use client';
import {useMemo,useState} from 'react';
import {jsPDF} from 'jspdf';

type F=Record<string,any>;
const AFA_LOGO='https://i.postimg.cc/02cV2JFP/www-afaescolasantsalvador-org.png';
const ROBOTICA_PHOTO='https://i.postimg.cc/9RdLMHz3/Captura-de-pantalla-2026-07-23-154054.png';
const ACTIVITIES:any={
  'Robòtica':{schedule:'Dimecres · 16:00–17:30 (berenar 16:00–16:45)', nonMember:20, member:15, second:0, third:0, extra:5, extraLabel:'Quota extraordinària al primer mes / preinscripció · Llibre'},
  'Acollida Matinal':{schedule:'Tots els dies · 08:00–09:15', nonMember:30, member:30, second:5, third:8.5, extra:0, extraLabel:''}
};
function activityConfig(name:string){return ACTIVITIES[name]||ACTIVITIES['Robòtica']}

function money(n:number){return `${Number(n||0).toFixed(2).replace('.',',')} €`}
function wrapText(doc:jsPDF,text:string,x:number,y:number,max:number,line=5){const lines=doc.splitTextToSize(String(text||'—'),max);doc.text(lines,x,y);return y+lines.length*line}

export default function Preinscripcio(){
 const [sent,setSent]=useState<any>(null);const [submitError,setSubmitError]=useState('');const [submitting,setSubmitting]=useState(false);
 const [f,setF]=useState<F>({activitat:'Robòtica',curs:'',grup:'',alumne:'',naixement:'',alergies:'',nese:'no',neseDetall:'',autoritzats:'',emergencia:'',tutor:'',dni:'',telefon:'',email:'',adreca:'',municipi:'Tarragona',cp:'',quota:'20',complements:'5',diners:'0',mitja:'Efectiu',isMember:false,childrenCount:'1',childOrder:'1',memberDiscount:'5',secondDiscount:'0',thirdDiscount:'0',imatge:'no'});
 const set=(k:string)=>(e:any)=>setF((x)=>({...x,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
 const cfg=activityConfig(f.activitat);
 const effectiveQuota=useMemo(()=>Number(cfg.nonMember),[f.activitat]);
 const memberDiscount=useMemo(()=>f.isMember?Math.max(0,Number(cfg.nonMember)-Number(cfg.member)):0,[f.isMember,f.activitat]);
 const discount=useMemo(()=>memberDiscount+(Number(f.childOrder)===2?Number(cfg.second||0):0)+(Number(f.childOrder)>=3?Number(cfg.third||0):0),[memberDiscount,f.childOrder,f.activitat]);
 const total=useMemo(()=>Math.max(0,effectiveQuota-discount)+Number(f.complements||0),[effectiveQuota,discount,f.complements]);
 const handleActivity=(name:string)=>{const c=activityConfig(name);setF((x:any)=>({...x,activitat:name,quota:String(x.isMember?c.member:c.nonMember),complements:String(c.extra||0),memberDiscount:String(Math.max(0,c.nonMember-c.member)),secondDiscount:String(c.second||0),thirdDiscount:String(c.third||0),childOrder:'1'}))};
 const handleMember=(isMember:boolean)=>{const c=activityConfig(f.activitat);setF((x:any)=>({...x,isMember,quota:String(c.nonMember),memberDiscount:String(Math.max(0,c.nonMember-c.member))}))};
 const discountLabel=useMemo(()=>{const p=[];if(f.isMember&&Number(f.memberDiscount)>0)p.push('Soci/a');if(Number(f.childOrder)===2&&Number(f.secondDiscount)>0)p.push('2n fill/a');if(Number(f.childOrder)>=3&&Number(f.thirdDiscount)>0)p.push('3r fill/a');return p.length?p.join(' · '):'Sense descompte'},[f]);
 async function submit(e:any){e.preventDefault();setSubmitError('');if(!f.normativa){setSubmitError('Cal acceptar les normatives i la informació bàsica de protecció de dades per continuar.');return}setSubmitting(true);const payload={...f,quota:effectiveQuota,descompte:discount,total,discountLabel,authorized_people:f.autoritzats?f.autoritzats.split('\n').filter(Boolean).map((name:string)=>({name})):[],emergency_contacts:f.emergencia?f.emergencia.split('\n').filter(Boolean).map((name:string)=>({name})):[],rules_accepted:Boolean(f.normativa),outing_accepted:Boolean(f.emergenciaOk),data_info_accepted:true,emergency_accepted:Boolean(f.emergenciaOk),signature_data:f.firmaVirtual||''};const r=await fetch('/api/public/registrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();setSubmitting(false);if(!r.ok){setSubmitError(j.error||'No s’ha pogut enviar el tràmit.');return}setSent({...j,total,discount,discountLabel});}
 async function logoData(){try{const r=await fetch(AFA_LOGO);const b=await r.blob();return await new Promise<string>(resolve=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.readAsDataURL(b)})}catch{return ''}}
 async function pdf(copy:number){if(!sent)return;const d=new jsPDF({unit:'mm',format:'a4'});const W=210,M=16,content=W-M*2;const logo=await logoData();const activityPhoto=f.activitat==='Robòtica'?await (async()=>{try{const r=await fetch(ROBOTICA_PHOTO);const b=await r.blob();return await new Promise<string>(resolve=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.readAsDataURL(b)})}catch{return ''}})():'';
   const purple='#5B21B6', light='#F3EDFF', ink='#17131F', muted='#6F6879', line='#E7E1EE';
   const section=(n:string,title:string,y:number)=>{d.setFillColor(purple);d.roundedRect(M,y,8,8,2,2,'F');d.setTextColor(255,255,255);d.setFont('helvetica','bold');d.setFontSize(9);d.text(n,M+4,y+5.5,{align:'center'});d.setTextColor(ink);d.setFontSize(12);d.text(title,M+13,y+5.7);d.setDrawColor(line);d.line(M,y+11,W-M,y+11);return y+17};
   const field=(label:string,value:string,x:number,y:number,w:number,h=13)=>{d.setFillColor(249,248,251);d.roundedRect(x,y,w,h,2.5,2.5,'F');d.setTextColor(muted);d.setFont('helvetica','bold');d.setFontSize(7.5);d.text(label.toUpperCase(),x+4,y+4.3);d.setTextColor(ink);d.setFont('helvetica','normal');d.setFontSize(9);wrapText(d,value||'—',x+4,y+9,w-8,4.3)};
   function header(){d.setFillColor(255,255,255);d.rect(0,0,W,25,'F');if(logo){try{d.addImage(logo,'PNG',M,5,22,15)}catch{}}else{d.setFillColor(193,0,225);d.text('A',M+3,14)}d.setTextColor(ink);d.setFont('helvetica','bold');d.setFontSize(14);d.text("AFA Escola Sant Salvador",M+27,11);d.setFont('helvetica','normal');d.setFontSize(7.5);d.setTextColor(muted);d.text('ACTIVA’T · Secretaria Virtual · Curs 2026–2027',M+27,16);d.setDrawColor(line);d.line(M,23,W-M,23);}
   function footer(){const page=d.getNumberOfPages();for(let p=1;p<=page;p++){d.setPage(p);d.setDrawColor(line);d.line(M,287,W-M,287);d.setTextColor(muted);d.setFontSize(7);d.text(`ACTIVA’T · Full de preinscripció d’activitat · ${sent.code}`,M,292);d.text(`CÒPIA ${copy} DE 2 · Pàgina ${p}/${page}`,W-M,292,{align:'right'})}}
   header();let y=34;d.setTextColor(purple);d.setFont('helvetica','bold');d.setFontSize(8);d.text('ACTIVA’T · SECRETARIA VIRTUAL',M,y);y+=7;d.setTextColor(ink);d.setFontSize(20);d.text("FULL DE PREINSCRIPCIÓ D’ACTIVITAT",M,y);y+=7;d.setTextColor(muted);d.setFont('helvetica','normal');d.setFontSize(9);d.text('AFA Escola Sant Salvador · Curs 2026–2027',M,y);d.setFillColor(light);d.roundedRect(137,32,57,22,4,4,'F');d.setTextColor(muted);d.setFontSize(7);d.text('CODI DE PREINSCRIPCIÓ',141,39);d.setTextColor(purple);d.setFont('helvetica','bold');d.setFontSize(11);d.text(sent.code,141,47);
   if(activityPhoto){try{d.addImage(activityPhoto,'PNG',M,55,42,24)}catch{}}
   d.setTextColor(ink);d.setFont('helvetica','bold');d.setFontSize(10);d.text(f.activitat,M+47,62);d.setFont('helvetica','normal');d.setFontSize(8);d.setTextColor(muted);d.text('Organitza: AFA Escola Sant Salvador',M+47,67);d.text(cfg.schedule,M+47,71);d.text(`Quota: ${money(cfg.nonMember)} · Soci/a AFA: ${money(cfg.member)}`,M+47,75);
   y=82;y=section('1','DADES DE L’ACTIVITAT I DE L’ALUMNE/A',y);field('Activitat',f.activitat,M,y,86);field('Curs / grup',`${f.curs} · ${f.grup}`,108,y,86);y+=16;field('Nom i cognoms',f.alumne,M,y,86);field('Data de naixement',f.naixement,108,y,86);y+=16;field('Al·lèrgies / informació rellevant',f.alergies||'—',M,y,86);field('Condició NESE',f.nese==='si'?'Sí':'No',108,y,86);y+=16;field('Observacions NESE',f.neseDetall||'—',M,y,178);y+=18;
  y=section('2 bis','PERSONES AUTORITZADES I CONTACTES',y);field('Persones autoritzades per recollir',f.autoritzats||'No indicades',M,y,86,23);field('Contactes d’emergència',f.emergencia||'No indicats',108,y,86,23);y+=28;
   y=section('2','DADES DEL REPRESENTANT LEGAL',y);field('Nom i cognoms',f.tutor,M,y,86);field('DNI / NIE / passaport',f.dni,108,y,86);y+=16;field('Telèfon',f.telefon,M,y,86);field('Correu electrònic',f.email,108,y,86);y+=16;field('Adreça',`${f.adreca}, ${f.cp} ${f.municipi}`,M,y,178);y+=18;
   y=section('3','CONDICIONS ECONÒMIQUES',y);field('Quota base',money(effectiveQuota),M,y,42);field('Descompte aplicat',`${money(discount)} · ${discountLabel}`,62,y,78);field('Complements',money(f.complements),142,y,54);y+=16;field('Diners lliurats',money(f.diners),M,y,55);field('Canvi calculat',money(Math.max(0,Number(f.diners||0)-total)),75,y,55);field('Mitjà de pagament',f.mitja,134,y,62);y+=17;d.setFillColor(light);d.roundedRect(M,y,178,16,3,3,'F');d.setTextColor(purple);d.setFont('helvetica','bold');d.setFontSize(8);d.text('IMPORT TOTAL',M+5,y+6);d.setFontSize(14);d.text(money(total),W-M-5,y+11,{align:'right'});d.setTextColor(muted);d.setFont('helvetica','normal');d.setFontSize(7);d.text('El pagament i les quotes es regeixen per la política de pagaments de l’AFA vigent.',M+5,y+13.5);y+=23;
   y=section('4','SITUACIÓ DE SOCI/A I FRATERNITAT',y);field('Condició de soci/a',f.isMember?'Soci/a':'No soci/a',M,y,58);field('Fills/es registrats/des',String(f.childrenCount||1),78,y,50);field('Ordre del fill/a',Number(f.childOrder)>=3?'3r o posterior':`${f.childOrder}r`,132,y,54);y+=18;
   y=section('5','DECLARACIONS I AUTORITZACIONS',y);d.setTextColor(ink);d.setFont('helvetica','normal');d.setFontSize(8.5);const decl=["La persona signant declara que les dades facilitades són certes i que té capacitat per autoritzar la participació de l’alumne/a.","Accepta les normes de funcionament de l’activitat, els horaris i les instruccions de l’organització.","La informació sobre imatge és separada i voluntària; el rebuig o la retirada d’aquesta autorització no impedirà la participació en l’activitat.","En cas d’incidència o urgència, l’AFA podrà contactar amb les persones indicades i adoptar les mesures raonables de protecció de l’infant, dins de les seves funcions."];for(const t of decl){y=wrapText(d,'• '+t,M,y,178,4.5)+2;if(y>270){d.addPage();header();y=34}}
   if(y>246){d.addPage();header();y=34}y=section('6','INFORMACIÓ BÀSICA SOBRE PROTECCIÓ DE DADES',y);d.setFont('helvetica','normal');d.setFontSize(7.7);d.setTextColor(ink);const privacy="Responsable: AFA Escola Sant Salvador. Domicili: Av. de Sant Salvador, 13, 43130 Tarragona. Contacte: contacte@afaescolasantsalvador.org. Finalitats: gestionar la preinscripció i participació en activitats, organitzar els grups, gestionar comunicacions relacionades amb l’activitat, atendre incidències i complir les obligacions legals que siguin aplicables. Base jurídica: gestió de la relació derivada de la sol·licitud/inscripció i, quan correspongui, el consentiment específic. Les dades estrictament necessàries no es basen en el consentiment quan existeixi una altra base jurídica aplicable. Conservació: les dades es conservaran durant el temps necessari per a la gestió de l’activitat i, posteriorment, durant els terminis exigits per obligacions legals o per a l’exercici i defensa de reclamacions. Drets: es pot sol·licitar l’accés, rectificació, supressió, oposició, limitació del tractament i, quan sigui aplicable, portabilitat, així com retirar un consentiment, mitjançant contacte amb l’AFA. També es pot presentar una reclamació davant l’Autoritat Catalana de Protecció de Dades (APDCAT) o l’autoritat de control competent. Destinataris: les dades només es comunicaran a tercers quan sigui necessari per gestionar l’activitat, existeixi una obligació legal o hi hagi una base jurídica que ho permeti. Quan s’utilitzin encarregats del tractament, aquests hauran d’oferir les garanties exigides per la normativa.";y=wrapText(d,privacy,M,y,178,4.1)+5;
   if(y>252){d.addPage();header();y=34}y=section('7','AUTORITZACIÓ D’IMATGE — TEXT EXPRESS DE LA DECISIÓ',y);y=wrapText(d,`Jo, ${f.tutor}, com a mare/pare o representant legal de l’alumne/a ${f.alumne}, ${f.imatge==='si'?'AUTORITZO':'NO AUTORITZO'} la captació, reproducció i publicació d’imatges o vídeos de l’alumne/a per a les finalitats de difusió i comunicació de les activitats de l’AFA. ${f.imatge==='si'?'Aquesta autorització és específica i voluntària.':'Aquesta negativa no impedeix la participació en l’activitat.'}`,M,y,178,4.5)+7;
   y=section('8','INFORMACIÓ SOBRE EL CODI I LA GESTIÓ DE PLACES',y);y=wrapText(d,`A cada preinscripció se li assigna un codi de preinscripció únic. Aquest codi permet identificar i consultar l’estat de la sol·licitud mitjançant contacte@afaescolasantsalvador.org. La gestió de places es farà per activitat. Per a aquest curs, tant Robòtica com Acollida Matinal tenen un límit de 12 alumnes cadascuna.`,M,y,178,4.5)+7;
  if(y>245){d.addPage();header();y=34}y=section('9','SIGNATURES',y);field('Representant legal',f.tutor,M,y,82,25);field('Lloc i data',`Tarragona, ${new Date().toLocaleDateString('ca-ES')}`,106,y,80,25);d.setTextColor(muted);d.setFontSize(7);d.text('La firma virtual es conserva amb l’expedient. Aquest document també es pot imprimir.',M,y+31);
   footer();d.save(`${sent.code}-copia-${copy}.pdf`)
 }
 if(sent)return <main className="container"><section className="hero"><span className="pill ok">✓ Tràmit registrat</span><h1>Preinscripció enviada</h1><p>La gestió ha quedat registrada. Guarda el codi <b>{sent.code}</b>; no cal iniciar sessió.</p></section><section className="card" style={{maxWidth:850}}><div className="row space"><div><span className="eyebrow">Codi de preinscripció</span><div className="codeBox">{sent.code}</div></div><span className="pill wait">En revisió</span></div><div className="detailGrid" style={{marginTop:22}}><div className="detailItem"><small>Alumne/a</small><b>{f.alumne}</b></div><div className="detailItem"><small>Activitat</small><b>{f.activitat}</b></div><div className="detailItem"><small>Condició</small><b>{f.isMember?'Soci/a':'No soci/a'} · {f.childOrder}r fill/a</b></div><div className="detailItem"><small>Import total</small><b>{money(sent.total)}</b></div></div><div className="section"><h3>Documents</h3><p className="muted small">Genera les dues còpies del full oficial amb la mateixa informació i una presentació preparada per imprimir.</p><div className="row"><button className="btn primary" onClick={()=>pdf(1)}>↓ PDF · Còpia 1</button><button className="btn secondary" onClick={()=>pdf(2)}>↓ PDF · Còpia 2</button></div></div></section></main>;
 return <main className="container"><section className="hero"><span className="eyebrow">Nou tràmit · Curs 2026–2027</span><h1>Preinscripció en pocs passos</h1><p>Completa les dades de l’alumne/a i del representant. Secretaria podrà corregir qualsevol dada després.</p></section><section className="heroPanel formIntro"><div><b>Abans de començar</b><p>Necessitaràs les dades de contacte, les persones autoritzades i l’acceptació dels textos legals.</p></div><div className="formSteps"><span className="active">1 <small>Dades</small></span><i></i><span>2 <small>Contactes</small></span><i></i><span>3 <small>Confirmació</small></span></div></section><form className="card form formCard" onSubmit={submit} style={{marginTop:20}}>
   <div className="full"><span className="eyebrow">1 · Activitat i alumne/a</span></div>
   <div className="field"><label>Activitat</label><select value={f.activitat} onChange={e=>handleActivity(e.target.value)}><option>Robòtica</option><option>Acollida Matinal</option></select></div>
   <div className="field"><label>Curs / grup</label><input value={f.curs} onChange={set('curs')}/></div>
   <div className="field"><label>Nom i cognoms de l’alumne/a</label><input value={f.alumne} onChange={set('alumne')} required/></div>
   <div className="field"><label>Data de naixement</label><input type="date" value={f.naixement} onChange={set('naixement')}/></div>
   <div className="field"><label>Al·lèrgies / informació rellevant</label><input value={f.alergies} onChange={set('alergies')}/></div>
   <div className="field"><label>Condició NESE</label><select value={f.nese} onChange={set('nese')}><option value="no">No</option><option value="si">Sí</option></select></div>
   <div className="field full"><label>Observacions NESE</label><textarea value={f.neseDetall} onChange={set('neseDetall')} rows={2}/></div>
   <div className="full sectionBreak"><span className="eyebrow">2 · Representant legal</span></div>
   {([['tutor','Nom i cognoms'],['dni','DNI/NIE/passaport'],['telefon','Telèfon'],['email','Correu electrònic'],['adreca','Adreça'],['municipi','Municipi'],['cp','Codi postal']] as any[]).map(([k,l])=><div className="field" key={k}><label>{l}</label><input type={k==='email'?'email':'text'} value={f[k]} onChange={set(k)} required={['tutor','email'].includes(k)}/></div>)}
   <div className="full sectionBreak"><span className="eyebrow">3 · Soci/a i descomptes</span><p className="muted small">Aquestes dades es poden corregir posteriorment des de Secretaria si la família s’ha equivocat.</p></div>
   <div className="field"><label>Condició de soci/a</label><select value={f.isMember?'si':'no'} onChange={e=>handleMember(e.target.value==='si')}><option value="si">Soci/a AFA</option><option value="no">No soci/a</option></select></div>
   <div className="field"><label>Nombre de fills/es registrats/des</label><input type="number" min="1" value={f.childrenCount} onChange={set('childrenCount')}/></div>
   <div className="field"><label>Ordre del fill/a</label><select value={f.childOrder} onChange={set('childOrder')}><option value="1">1r fill/a</option><option value="2">2n fill/a</option><option value="3">3r fill/a o posterior</option></select></div>
   <div className="field"><label>Descompte soci/a (€) <span className="muted small">configurat</span></label><input type="number" value={memberDiscount} readOnly/></div>
   <div className="field"><label>Descompte 2n fill/a (€) <span className="muted small">configurat</span></label><input type="number" value={cfg.second} readOnly/></div>
   <div className="field"><label>Descompte 3r fill/a (€) <span className="muted small">configurat</span></label><input type="number" value={cfg.third} readOnly/></div>
   <div className="full discountBox"><div className="discountLine"><span>Quota base</span><b>{money(f.quota)}</b></div><div className="discountLine"><span>{discountLabel}</span><b>− {money(discount)}</b></div><div className="discountLine"><span>Complements</span><b>+ {money(f.complements)}</b></div><div className="totalLine row space"><span>Import total</span><span>{money(total)}</span></div></div>
   <div className="field"><label>Quota base (€)</label><input type="number" step="0.01" min="0" value={effectiveQuota} readOnly/><span className="muted small">Soci/a AFA: {money(cfg.member)}</span></div><div className="field"><label>Complement extraordinari (€)</label><input type="number" step="0.01" min="0" value={f.complements} onChange={set('complements')} readOnly={f.activitat==='Robòtica'||f.activitat==='Acollida Matinal'}/><span className="muted small">{cfg.extraLabel||'Sense quota extraordinària'}</span></div>
   <div className="field"><label>Diners lliurats (€)</label><input type="number" step="0.01" min="0" value={f.diners} onChange={set('diners')}/></div><div className="field"><label>Mitjà de pagament</label><select value={f.mitja} onChange={set('mitja')}><option>Efectiu</option><option>Transferència</option><option>Altres</option></select></div>
  <div className="full sectionBreak"><span className="eyebrow">4 · Persones autoritzades i contactes</span></div><div className="field full"><label>Persones autoritzades per recollir</label><textarea value={f.autoritzats} onChange={set('autoritzats')} rows={3} placeholder="Nom · telèfon · relació"/></div><div className="field full"><label>Contactes d’emergència</label><textarea value={f.emergencia} onChange={set('emergencia')} rows={3} placeholder="Nom · telèfon · relació"/></div><div className="full sectionBreak"><span className="eyebrow">5 · Normativa i firma virtual</span><div className="notice" style={{marginTop:10}}>La preinscripció no implica l’adjudicació automàtica de plaça. La informació d’imatge és separada i voluntària.</div><details className="legalDetails"><summary>Consultar el resum legal</summary><p>Responsable: AFA Escola Sant Salvador. Les dades s’utilitzen per gestionar la preinscripció, les activitats, les comunicacions i les obligacions legals. Pots exercir els teus drets escrivint a contacte@afaescolasantsalvador.org.</p></details></div>
  <label className="legalCheck full"><input type="checkbox" checked={Boolean(f.normativa)} onChange={e=>setF((x:any)=>({...x,normativa:e.target.checked}))}/><span><b>Accepto les normatives i els textos legals</b><small>He llegit el resum legal i confirmo que les dades són correctes.</small></span></label><label className="legalCheck full"><input type="checkbox" checked={Boolean(f.emergenciaOk)} onChange={e=>setF((x:any)=>({...x,emergenciaOk:e.target.checked}))}/><span><b>Autoritzo el contacte en cas d’emergència</b><small>Opcional: permet contactar amb les persones indicades si hi ha una incidència.</small></span></label><div className="field full"><label>Firma virtual del representant legal</label><input value={f.firmaVirtual||''} onChange={set('firmaVirtual')} placeholder="Escriu el teu nom complet" required/><span className="muted small">Aquesta firma confirma la sol·licitud.</span></div><div className="field full"><label>Autorització d’imatge</label><select value={f.imatge} onChange={set('imatge')}><option value="no">No autoritzo</option><option value="si">Sí, autoritzo</option></select></div>
  {submitError&&<div className="notice errorNotice full" role="alert">{submitError}</div>}<div className="full row space formSubmit"><span className="muted small">Rebràs un codi per consultar la gestió.</span><button className="btn primary" disabled={submitting}>{submitting?'Enviant…':'Enviar preinscripció →'}</button></div>
 </form></main>
}
