import {NextRequest,NextResponse} from 'next/server';
import {adminSupabase} from '@/lib/supabase';
import {demoRegistrations} from '@/lib/demo';

function normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()}
function surnameMatches(student:string,surname:string){const wanted=normalize(surname);const parts=normalize(student).split(/\s+/).filter(Boolean);return parts.slice(1,3).includes(wanted)||parts.includes(wanted)}
function safe(record:any){return {code:record.code,status:record.status,activity:record.activity_name,student:record.student_name,representative:record.representative_name,birthDate:record.birth_date,total:record.total_amount,paid:record.paid_amount,emergencyContacts:record.emergency_contacts||[]}}

export async function POST(req:NextRequest){const body=await req.json();const code=String(body.code||'').trim().toUpperCase();const surname=String(body.surname||'').trim();const birthDate=String(body.birthDate||'').trim();if(!birthDate||(!code&&!surname))return NextResponse.json({error:'Indica el número de preinscripció o el primer cognom i la data de naixement.'},{status:400});try{const sb=adminSupabase();let query=sb.from('registrations').select('id,code,status,activity_name,student_name,representative_name,birth_date,total_amount,paid_amount,emergency_contacts');const {data,error}=code?await query.eq('code',code).eq('birth_date',birthDate).maybeSingle():await query.eq('birth_date',birthDate);if(error)throw error;if(code&&data)return NextResponse.json({registration:safe(data)});if(!code){const rows=Array.isArray(data)?data:(data?[data]:[]);const matches=rows.filter((record:any)=>surnameMatches(record.student_name,surname));if(matches.length===1)return NextResponse.json({registration:safe(matches[0])});if(matches.length>1)return NextResponse.json({matches:matches.map(safe)});}}catch{}
 const candidates=demoRegistrations.filter(record=>record.birth_date===birthDate&&(!code? surnameMatches(record.student_name,surname):record.code===code));if(candidates.length===1)return NextResponse.json({registration:safe({...candidates[0],birth_date:candidates[0].birth_date,emergency_contacts:candidates[0].emergency_contacts})});if(candidates.length>1)return NextResponse.json({matches:candidates.map(safe)});return NextResponse.json({error:'No hem trobat cap inscripció exacta amb aquestes dades.'},{status:404})}

export async function PATCH(req:NextRequest){const body=await req.json();const code=String(body.code||'').trim().toUpperCase();const surname=String(body.surname||'').trim();const birthDate=String(body.birthDate||'').trim();const contacts=Array.isArray(body.emergencyContacts)?body.emergencyContacts.map((contact:any)=>({name:String(contact.name||'').trim(),phone:String(contact.phone||'').trim(),relation:String(contact.relation||'').trim()})).filter((contact:any)=>contact.name&&contact.phone):[];if(!birthDate||(!code&&!surname))return NextResponse.json({error:'Falten les dades per identificar la inscripció.'},{status:400});try{const sb=adminSupabase();const {data:rows,error}=await sb.from('registrations').select('id,code,status,activity_name,student_name,representative_name,birth_date,total_amount,paid_amount,emergency_contacts').eq('birth_date',birthDate);if(error)throw error;const matches=(rows||[]).filter((record:any)=>(code?record.code===code:surnameMatches(record.student_name,surname)));if(matches.length!==1)return NextResponse.json({error:'La identificació no correspon a una única inscripció.'},{status:409});const {data,error:updateError}=await sb.from('registrations').update({emergency_contacts:contacts}).eq('id',matches[0].id).select('id,code,status,activity_name,student_name,representative_name,birth_date,total_amount,paid_amount,emergency_contacts').single();if(updateError)throw updateError;return NextResponse.json({registration:safe(data)})}catch{return NextResponse.json({error:'No s’han pogut actualitzar els contactes. Torna-ho a provar.'},{status:500})}}
