import {NextRequest,NextResponse} from 'next/server';
import {adminSupabase} from '@/lib/supabase';
import {demoRegistrations} from '@/lib/demo';

function normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase()}
function surnameMatches(student:string,surname:string){const wanted=normalize(surname);return normalize(student).split(/\s+/).filter(Boolean).slice(1,3).includes(wanted)}
function safe(record:any){return {code:record.code,status:record.status,activity:record.activity_name,student:record.student_name,representative:record.representative_name,birthDate:record.birth_date,total:record.total_amount,paid:record.paid_amount,emergencyContacts:record.emergency_contacts||[],authorizedPeople:record.authorized_people||[]}}
function cleanPeople(value:any){return Array.isArray(value)?value.map((person:any)=>({name:String(person.name||'').trim(),phone:String(person.phone||'').trim(),relation:String(person.relation||'').trim()})).filter((person:any)=>person.name&&person.phone):[]}

export async function POST(req:NextRequest){const body=await req.json();const code=String(body.code||'').trim().toUpperCase();const surname=String(body.surname||'').trim();const birthDate=String(body.birthDate||'').trim();if(!code&&!surname)return NextResponse.json({error:'Indica el número de preinscripció o el primer cognom.'},{status:400});if(!code&&!birthDate)return NextResponse.json({error:'Per buscar per cognom cal indicar també la data de naixement.'},{status:400});try{const sb=adminSupabase();const columns='id,code,status,activity_name,student_name,representative_name,birth_date,total_amount,paid_amount,emergency_contacts,authorized_people';const query=sb.from('registrations').select(columns);const {data,error}=code?await query.eq('code',code).maybeSingle():await query.eq('birth_date',birthDate);if(error)throw error;if(code&&data)return NextResponse.json({registration:safe(data)});const rows=Array.isArray(data)?data:(data?[data]:[]);const matches=rows.filter((record:any)=>surnameMatches(record.student_name,surname));if(matches.length===1)return NextResponse.json({registration:safe(matches[0])});if(matches.length>1)return NextResponse.json({matches:matches.map(safe)});}catch{}
 const matches=demoRegistrations.filter(record=>code?record.code===code:record.birth_date===birthDate&&surnameMatches(record.student_name,surname));if(matches.length===1)return NextResponse.json({registration:safe(matches[0])});if(matches.length>1)return NextResponse.json({matches:matches.map(safe)});return NextResponse.json({error:'No hem trobat cap inscripció exacta amb aquestes dades.'},{status:404})}

export async function PATCH(req:NextRequest){const body=await req.json();const code=String(body.code||'').trim().toUpperCase();const surname=String(body.surname||'').trim();const birthDate=String(body.birthDate||'').trim();if(!code&&!surname)return NextResponse.json({error:'Falten les dades per identificar la inscripció.'},{status:400});if(!code&&!birthDate)return NextResponse.json({error:'Per buscar per cognom cal indicar també la data de naixement.'},{status:400});const emergencyContacts=cleanPeople(body.emergencyContacts);const authorizedPeople=cleanPeople(body.authorizedPeople);try{const sb=adminSupabase();const columns='id,code,status,activity_name,student_name,representative_name,birth_date,total_amount,paid_amount,emergency_contacts,authorized_people';const query=sb.from('registrations').select(columns);const {data,error}=code?await query.eq('code',code):await query.eq('birth_date',birthDate);if(error)throw error;const matches=(rows=>rows.filter((record:any)=>code||surnameMatches(record.student_name,surname)))(Array.isArray(data)?data:(data?[data]:[]));if(matches.length!==1)return NextResponse.json({error:'La identificació no correspon a una única inscripció.'},{status:409});const {data:updated,error:updateError}=await sb.from('registrations').update({emergency_contacts:emergencyContacts,authorized_people:authorizedPeople}).eq('id',matches[0].id).select(columns).single();if(updateError)throw updateError;return NextResponse.json({registration:safe(updated)})}catch{return NextResponse.json({error:'No s’han pogut actualitzar els contactes. Torna-ho a provar.'},{status:500})}}
